### ISSUE TITLE
Vagrant Error: undefined method `plugins_enabled?'

### ISSUE THREAD

**Issue by jeromebridge** [jeromebridge/yet-another-admin-system-dev-env#24]
```
matt@matt-Pangolin-Performance:~/Git/yet-another-admin-system-dev-env$ vagrant up

/home/matt/Git/yet-another-admin-system-dev-env/Vagrantfile:12:in `block in <top (required)>': undefined method `plugins_enabled?' for Vagrant:Module (NoMethodError)

    from /usr/lib/ruby/vendor_ruby/vagrant/config/v2/loader.rb:37:in `call'

    from /usr/lib/ruby/vendor_ruby/vagrant/config/v2/loader.rb:37:in `load'

    from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:104:in `block (2 levels) in load'

    from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:98:in `each'

    from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:98:in `block in load'

    from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:95:in `each'

    from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:95:in `load'

    from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:265:in `config_global'

    from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:519:in `block in action_runner'

    from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:36:in `call'

    from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:36:in `run'

    from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:283:in `hook'

    from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:139:in `initialize'

    from /usr/bin/vagrant:105:in `new'

    from /usr/bin/vagrant:105:in `<main>'
```

**Comment by jeromebridge** [comment]
It looks like the environment is super out of date when this error happens. Update all your packages and try again: `sudo apt-get update && sudo apt-get upgrade -y`

**Comment by jeromebridge** [comment]
Found this reference: https://github.com/mitchellh/vagrant/issues/7465
